version: '3.8'

services: 
    btd:
        container_name: btd
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment: 
            BASE_PATH: "/opt/data"
            RM_HOST: "rm:8005"
        volumes:
            - ../repos:/opt/data
        ports: 
            - 8004:8004

networks:
    default:
        external:
            name: proxynet