apiVersion: apps/v1
kind: Deployment
metadata:
  name: btd-deployment
  labels:
    app: btd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btd
  template:
    metadata:
      labels:
        app: btd
    spec:
      imagePullSecrets:
        - name: dockerregistrykey
      containers:
        - name: btd
          image: {{ .Values.registry }}:{{ .Values.tag }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8004
          env:
            - name: RM_HOST
              value: "rm-service:8005"
